---
version: '2'

networks:
  scraper:
    driver: bridge

services:
  redis:
    image: bitnami/redis:latest
    container_name: redis-duplicates
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # Allows Redis to start without a password (local dev set up only so doesn't matter)
      - REDIS_AOF_ENABLED=yes
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - scraper

volumes:
  redis_data: